training:
  model: GrIS_HybridFlow
  epochs: 25
  batch_size: 250
  generative_scaling_constant: 0.8
  test_split_ratio: 0.05
  verbose: True
  plot_loss: True
  save_metrics: True

data:
  dir: C:/Users/Peter/Documents/Research/data/proj_MAIN_2100
  ssp: all              # all, ssp370, ssp245, ssp126, ssp119, ssp585, sspndc
  ice_source: gris      # gris, glaciers, ais
  region: None

model:
  flow:
    num_flow_transformations: 5
    hidden_features: 128
  conditional: False

visualizations:
  generate_plots:      # prediction_uncertainty, residuals_histogram, cross_validation_plots
    - prediction_uncertainty
    - residuals_histogram
    - cross_validation_plots
  save_plots: True

